# The straight line on the same curve

A polynomial regression of degree $1$ is ordinary simple regression. Fitting it to the quadratic table shows what the unused column $x^2$ was paying for. The comparison is fair because both models are scored by the same residual sum of squares.


## The degree-one solution

The same sums $\sum y = 35$ and $\sum xy = 20$ give the line at once. Symmetry still separates the blocks, and degree $1$ simply never opens the equation for $b_2$:

$$
5b_0 = 35 \Longrightarrow b_0 = 7, \qquad 10b_1 = 20 \Longrightarrow b_1 = 2.
$$

The line is $7 + 2x$. Its predictions are

$$
3,\ 5,\ 7,\ 9,\ 11.
$$

Against $y = 10, 0, 1, 8, 16$ the residuals are

$$
7,\ -5,\ -6,\ -1,\ 5,
$$

and

$$
\mathrm{RSS}_1 = 49 + 25 + 36 + 1 + 25 = 136.
$$

The quadratic residual sum was $10$. The column $x^2$ reduced the residual sum by $126$, using one coefficient. The slope did not move: it is $2$ in both fits, because $x$ is orthogonal to $x^2$ on this design. What the line missed is curvature, not tilt.


In [1]:
# Degree 1 uses the same slope and a different intercept. RSS rises from 10 to 136.
x = [-2, -1, 0, 1, 2]
y = [10, 0, 1, 8, 16]
intercept = sum(y) / len(y)
slope = sum(xi * yi for xi, yi in zip(x, y)) / sum(xi ** 2 for xi in x)
fitted = [intercept + slope * xi for xi in x]
errors = [yi - yh for yi, yh in zip(y, fitted)]
rss = sum(error ** 2 for error in errors)
print("line", intercept, slope)
print("fitted", fitted)
print("residuals", errors, "RSS", rss)
assert intercept == 7 and slope == 2
assert fitted == [3, 5, 7, 9, 11]
assert errors == [7, -5, -6, -1, 5]
assert rss == 136
assert 136 - 10 == 126


line 7.0 2.0
fitted [3.0, 5.0, 7.0, 9.0, 11.0]
residuals [7.0, -5.0, -6.0, -1.0, 5.0] RSS 136.0


## Where the line sits relative to the parabola

At the five sample points the parabola $1 + 2x + 3x^2$ predicts $9, 2, 1, 6, 17$. The line predicts $3, 5, 7, 9, 11$. The gap, parabola minus line, is

$$
6,\ -3,\ -6,\ -3,\ 6 = 3(x^2 - 2),
$$

since $1 + 2x + 3x^2 - (7 + 2x) = 3x^2 - 6$. The line is too low at the ends and too high in the middle. That sign pattern, $+,-,-,-,+$, is the squared term seen through a degree that cannot represent it.

At $x = 0$ the two predictions are $1$ and $7$. The line's intercept is the average response, not the value of the parabola at the origin.


In [2]:
# The gap between the quadratic mean and the line is 3(x^2 - 2).
x = [-2, -1, 0, 1, 2]
parabola = [1 + 2 * xi + 3 * xi ** 2 for xi in x]
line = [7 + 2 * xi for xi in x]
gap = [a - b for a, b in zip(parabola, line)]
print("gap", gap)
assert gap == [3 * (xi ** 2 - 2) for xi in x]
assert gap == [6, -3, -6, -3, 6]


gap [6, -3, -6, -3, 6]


## One change: fit the pure parabola, with no residual

If the responses are $9, 2, 1, 6, 17$, the quadratic residual sum is zero. The line is unchanged in its slope, because $\sum x y$ for this pure parabola equals $\sum x(1 + 2x + 3x^2) = 2\sum x^2 = 20$, the same sum as before. The line's residual sum of squares becomes the sum of squares of $6, -3, -6, -3, 6$, which is $36 + 9 + 36 + 9 + 36 = 126$. All $126$ that the quadratic removed from the noisy table are present here as pure curvature, with no extra noise.


In [3]:
# On the exact parabola the line still has slope 2 and RSS 126.
x = [-2, -1, 0, 1, 2]
y = [9, 2, 1, 6, 17]
slope = sum(xi * yi for xi, yi in zip(x, y)) / sum(xi ** 2 for xi in x)
intercept = sum(y) / len(y)
rss = sum((yi - intercept - slope * xi) ** 2 for xi, yi in zip(x, y))
print("line on the pure parabola", intercept, slope, "RSS", rss)
assert slope == 2 and intercept == 7
assert rss == 126


line on the pure parabola 7.0 2.0 RSS 126.0


## Pitfall

A slope of $2$ in the linear fit does not mean the data are linear with slope $2$. The same slope appears in $1 + 2x + 3x^2$. Orthogonality let the linear coefficient keep its value when the quadratic term was added. On a design that is not symmetric, adding $x^2$ would have changed $b_1$. Reading $7 + 2x$ as the description of the table, rather than as the degree-$1$ projection of the table, drops the $126$ residual sum that the next degree explains.


In [4]:
# Both degrees report the slope 2. Their residual sums do not agree.
print("shared slope", 2)
print("degree-1 RSS", 136)
print("degree-2 RSS", 10)
assert 136 != 10


shared slope 2
degree-1 RSS 136
degree-2 RSS 10


## Summary

- The least-squares line is $7 + 2x$, with residuals $7, -5, -6, -1, 5$ and $\mathrm{RSS} = 136$.
- The quadratic uses the same slope and reduces the residual sum by $126$.
- The gap between the parabola and the line on this grid is $3(x^2 - 2)$.
