# $R^2$ for a polynomial

The decomposition $\mathrm{TSS} = \mathrm{SSR} + \mathrm{RSS}$ holds for every polynomial that contains an intercept, because the residuals are orthogonal to the column of ones and the fitted vector lies in the column space. Adjusted $R^2$ then charges the polynomial for every extra power.


## The five-point sums of squares

The responses $10, 0, 1, 8, 16$ have mean $7$. Their total sum of squares is

$$
\begin{aligned}
\mathrm{TSS}
&= (10-7)^2 + (0-7)^2 + (1-7)^2 + (8-7)^2 + (16-7)^2 \\
&= 9 + 49 + 36 + 1 + 81 = 176.
\end{aligned}
$$

The quadratic fit has $\mathrm{RSS}_2 = 10$, so $\mathrm{SSR}_2 = 166$ and

$$
R^2_2 = \dfrac{166}{176} = \dfrac{83}{88}.
$$

With $n = 5$ and $p = 3$,

$$
\bar R^2_2
= 1 - \dfrac{10/2}{176/4}
= 1 - \dfrac{5}{44}
= \dfrac{39}{44}.
$$

The line has $\mathrm{RSS}_1 = 136$, so $\mathrm{SSR}_1 = 40$ and

$$
R^2_1 = \dfrac{40}{176} = \dfrac{5}{22}.
$$

Its adjusted value uses $p = 2$:

$$
\bar R^2_1
= 1 - \dfrac{136/3}{176/4}
= 1 - \dfrac{136}{132}
= 1 - \dfrac{34}{33}
= -\dfrac{1}{33}.
$$

Adjusted $R^2$ is negative when $\mathrm{RSS}/(n-p)$ exceeds $\mathrm{TSS}/(n-1)$. After paying for two coefficients, the line leaves more residual variance than the raw responses had. The ordinary $R^2$ hid that: $5/22$ is positive because a ratio of sums of squares cannot see the degrees of freedom.


In [1]:
# R-squared and adjusted R-squared for the line and the quadratic.
from fractions import Fraction
y = [10, 0, 1, 8, 16]
mean = Fraction(sum(y), 5)
tss = sum((yi - mean) ** 2 for yi in y)
rss_line, rss_quad = Fraction(136), Fraction(10)
r2_line = 1 - rss_line / tss
r2_quad = 1 - rss_quad / tss
adj_line = 1 - (rss_line / 3) / (tss / 4)
adj_quad = 1 - (rss_quad / 2) / (tss / 4)
print("TSS", tss)
print("line", r2_line, adj_line)
print("quadratic", r2_quad, adj_quad)
assert tss == 176
assert r2_quad == Fraction(83, 88) and adj_quad == Fraction(39, 44)
assert r2_line == Fraction(5, 22) and adj_line == Fraction(-1, 33)
assert tss == (tss - rss_quad) + rss_quad


TSS 176
line 5/22 -1/33
quadratic 83/88 39/44


## One change: the exact parabola

If $y = 9, 2, 1, 6, 17$, then $\mathrm{RSS}_2 = 0$ and $R^2_2 = 1$. These values have mean $7$ and

$$
\mathrm{TSS} = (9-7)^2 + (2-7)^2 + (1-7)^2 + (6-7)^2 + (17-7)^2 = 4 + 25 + 36 + 1 + 100 = 166.
$$

The line still leaves $\mathrm{RSS}_1 = 126$, so its $R^2$ is $40/166 = 20/83$. Adjusted $R^2$ of the quadratic is also $1$ when the residual sum is zero. A perfect fit is not reduced by the penalty. The penalty matters when the residual sum is positive and $p$ is large.


In [2]:
# A zero residual sum gives R-squared 1 before and after the adjustment.
from fractions import Fraction
y = [9, 2, 1, 6, 17]
mean = Fraction(sum(y), 5)
tss = sum((yi - mean) ** 2 for yi in y)
rss = 0
adjusted = 1 - (Fraction(rss, 2)) / (tss / 4)
print("TSS", tss, "adjusted", adjusted)
assert tss == 166
assert adjusted == 1


TSS 166 adjusted 1


## Pitfall

$R^2_2 = 83/88$ does not say that a cubic is unnecessary, and $\bar R^2_1 < 0$ does not say that the slope is zero. The next lesson tests one added power with an $F$ statistic. Adjusted $R^2$ is only the variance comparison written above. On this table it ranks the quadratic above the line, $39/44$ against $-1/33$, and that ranking agrees with the residual sums $10$ and $136$.


In [3]:
# Adjusted R-squared ranks the two models in the same order as the residual sums.
from fractions import Fraction
print("quadratic better on RSS", 10 < 136)
print("quadratic better on adjusted R^2", Fraction(39, 44) > Fraction(-1, 33))
assert Fraction(39, 44) > 0 > Fraction(-1, 33)


quadratic better on RSS True
quadratic better on adjusted R^2 True


## Summary

- $\mathrm{TSS} = 176$. The quadratic explains $166$ of it: $R^2 = 83/88$ and $\bar R^2 = 39/44$.
- The line explains $40$: $R^2 = 5/22$ and $\bar R^2 = -1/33$.
- A negative adjusted $R^2$ means the residual variance, after the coefficients, exceeds the variance of $y$.
