# The question on the manifest

A passenger ship is in trouble. For each person on the manifest, the question is the one the contest asks:

> Predict which passengers are transported to an alternate dimension.

The column that records the answer is `Transported`. `True` means that passenger was transported. `False` means that passenger stayed.

You already have three tables in `data/`, beside these notebooks.

| File | Rows | What it contains |
|---|---:|---|
| `train.csv` | 8693 | The clues, and the true fate |
| `test.csv` | 4277 | The same clues, with the fate left out |
| `sample_submission.csv` | 4277 | The two-column shape a contest answer file uses |

The 8693 fates are the record you can study. The 4277 fates are not in the file, so this path never scores them.


In [2]:
# Locate the contest tables beside this notebook, or under the course root.
from pathlib import Path
import csv

def manifest_path(name):
    here = Path.cwd()
    for folder in [here, *here.parents]:
        nested = folder / "13-Spaceship Titanic" / "data" / name
        direct = folder / "data" / name
        if nested.exists():
            return nested
        if direct.exists() and (folder / "data" / "sample_submission.csv").exists():
            return direct
    raise FileNotFoundError(name)

def read_manifest(name):
    with manifest_path(name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))

train = read_manifest("train.csv")
test = read_manifest("test.csv")
submission = read_manifest("sample_submission.csv")
print(len(train), len(test), len(submission))
print(train[0]["PassengerId"], train[0]["Name"])


8693 4277 4277
0001_01 Maham Ofracculy


In [3]:
# The training file has the answer column. The test file and the sample file do not.
print(list(train[0].keys()))
print("Transported" in test[0])
print(list(submission[0].keys()))
assert len(train) == 8693
assert len(test) == 4277
assert len(submission) == 4277
assert "Transported" in train[0]
assert "Transported" not in test[0]
assert list(submission[0].keys()) == ["PassengerId", "Transported"]


['PassengerId', 'HomePlanet', 'CryoSleep', 'Cabin', 'Destination', 'Age', 'VIP', 'RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck', 'Name', 'Transported']
False
['PassengerId', 'Transported']


## Pitfall

`sample_submission.csv` answers `False` for every test passenger. That file shows the required columns. It is not a studied prediction, and it cannot be graded from these tables.

## Summary

Learn from 8693 known fates. Deliver a prediction only in the shape `PassengerId`, `Transported`. Leave the 4277 unknown fates ungraded.
