# The fate is almost a coin toss

Count the training fates before using any clue.

$$
\begin{aligned}
4378 + 4315 &= 8693 \\
4378 - 4315 &= 63
\end{aligned}
$$

So 4378 passengers were transported and 4315 stayed. The constant prediction "everyone was transported" is right on 4378 rows. The constant prediction "everyone stayed" is right on 4315 rows.

The same gap, written as a distance from one half:

$$
\dfrac{4378}{8693} - \dfrac{1}{2}
= \dfrac{2 \cdot 4378 - 8693}{2 \cdot 8693}
= \dfrac{8756 - 8693}{17386}
= \dfrac{63}{17386}.
$$

Any useful rule has to beat 4378 correct rows. A rule that ignores the clues cannot do better than that, because 4378 is the larger of the two fate counts.


In [2]:
# Locate the contest tables beside this notebook, or under the course root.
from pathlib import Path
import csv

def manifest_path(name):
    here = Path.cwd()
    for folder in [here, *here.parents]:
        nested = folder / "13-Spaceship Titanic" / "data" / name
        direct = folder / "data" / name
        if nested.exists():
            return nested
        if direct.exists() and (folder / "data" / "sample_submission.csv").exists():
            return direct
    raise FileNotFoundError(name)

def read_manifest(name):
    with manifest_path(name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))

train = read_manifest("train.csv")
test = read_manifest("test.csv")
submission = read_manifest("sample_submission.csv")
print(len(train), len(test), len(submission))
print(train[0]["PassengerId"], train[0]["Name"])


8693 4277 4277
0001_01 Maham Ofracculy


In [3]:
# Count the two fates and the gap above one half.
from fractions import Fraction
transported = sum(row["Transported"] == "True" for row in train)
stayed = sum(row["Transported"] == "False" for row in train)
gap = transported - stayed
above_half = Fraction(transported, len(train)) - Fraction(1, 2)
print(transported, stayed, gap)
print(above_half)
assert transported == 4378
assert stayed == 4315
assert transported + stayed == 8693
assert gap == 63
assert above_half == Fraction(63, 17386)


4378 4315 63
63/17386


## Pitfall

"Almost half" still has a majority. Predicting that everyone stayed loses those 63 passengers to the even simpler prediction that everyone was transported. The sample submission predicts that everyone stayed, so on a test set with the same mix it would sit on the smaller side of this coin.

## Summary

The floor on the training manifest is 4378 of 8693. The extra is exactly $63/17386$ above one half.
