# Where the manifest is blank

The fate is filled on all 8693 training rows, and so is `PassengerId`. Every clue column has some empty cells. An empty cell is `""` in the file.

| Column | Blank cells |
|---|---:|
| `PassengerId` | 0 |
| `HomePlanet` | 201 |
| `CryoSleep` | 217 |
| `Cabin` | 199 |
| `Destination` | 182 |
| `Age` | 179 |
| `VIP` | 203 |
| `RoomService` | 181 |
| `FoodCourt` | 183 |
| `ShoppingMall` | 208 |
| `Spa` | 183 |
| `VRDeck` | 188 |
| `Name` | 200 |
| `Transported` | 0 |

The test file has the same kind of gaps in the clue columns, and it has no `Transported` column at all. Those are different absences. A blank age is a missing clue. A missing fate is the question.


In [2]:
# Locate the contest tables beside this notebook, or under the course root.
from pathlib import Path
import csv

def manifest_path(name):
    here = Path.cwd()
    for folder in [here, *here.parents]:
        nested = folder / "13-Spaceship Titanic" / "data" / name
        direct = folder / "data" / name
        if nested.exists():
            return nested
        if direct.exists() and (folder / "data" / "sample_submission.csv").exists():
            return direct
    raise FileNotFoundError(name)

def read_manifest(name):
    with manifest_path(name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))

train = read_manifest("train.csv")
test = read_manifest("test.csv")
submission = read_manifest("sample_submission.csv")
print(len(train), len(test), len(submission))
print(train[0]["PassengerId"], train[0]["Name"])


8693 4277 4277
0001_01 Maham Ofracculy


In [3]:
# Count empty strings in every training column.
expected = {
    "PassengerId": 0,
    "HomePlanet": 201,
    "CryoSleep": 217,
    "Cabin": 199,
    "Destination": 182,
    "Age": 179,
    "VIP": 203,
    "RoomService": 181,
    "FoodCourt": 183,
    "ShoppingMall": 208,
    "Spa": 183,
    "VRDeck": 188,
    "Name": 200,
    "Transported": 0,
}
blanks = {column: 0 for column in expected}
for row in train:
    for column in blanks:
        blanks[column] += row[column] == ""
for column, count in blanks.items():
    print(f"{column} {count}")
assert blanks == expected
assert sum(row["Transported"] == "" for row in train) == 0


PassengerId 0
HomePlanet 201
CryoSleep 217
Cabin 199
Destination 182
Age 179
VIP 203
RoomService 181
FoodCourt 183
ShoppingMall 208
Spa 183
VRDeck 188
Name 200
Transported 0


## Pitfall

Filling every blank with the most common value makes the table look complete and erases the fact that the cell was empty. Candra Jacostaffey, `0006_02`, has an empty `VRDeck`. That empty cell is one of the 188. Her other known bills are zero, and her `CryoSleep` cell is `True`. The empty bill and the cryosleep flag are both part of her row.

## Summary

Fourteen columns, two of them complete. The other twelve carry between 179 and 217 blanks. Later rules will say what they do when the cell they need is empty.
