# House 1, before any average

The first training row is house `Id` 1, in College Creek (`CollgCr`). Read the pieces that have to add up before trusting a model.

It is subclass 60, a two-story house from 1946 or later, and `HouseStyle` agrees: `2Story`. Zoning is `RL`, residential low density. The lot has 65 feet of frontage and 8450 square feet of area. The street is paved. `Alley` is `NA`, which the codebook defines as no alley. The shape is regular, the land is level, the utilities are public, the lot sits inside the block, and the slope is gentle.

`OverallQual` is 7 and `OverallCond` is 5. It was built in 2003 and the remodel year is also 2003. The roof is a gable with standard shingles. The exterior is vinyl, with 196 square feet of brick-face veneer. Exterior quality is `Gd` and the condition is `TA`, typical. The foundation is poured concrete.

The basement is quality `Gd`, condition `TA`, exposure `No` (the codebook's word for a basement with no exposure, which is different from `NA`). The finished area is 706, the second finished area is 0, and the unfinished area is 150.

$$
706 + 0 + 150 = 856
$$

and `TotalBsmtSF` is 856. Above ground, the first floor is 856, the second floor is 854, and the low-quality finished area is 0.

$$
856 + 854 + 0 = 1710
$$

and `GrLivArea` is 1710. There are 2 full baths and 1 half bath above grade, 3 bedrooms, 1 kitchen of quality `Gd`, and 8 rooms above grade. There is no fireplace: `Fireplaces` is 0 and `FireplaceQu` is `NA`. The garage is attached, built in 2003, finished, with 2 cars and 548 square feet. The open porch is 61 square feet. There is no pool, no fence, and no miscellaneous feature. It sold in February 2008 by a conventional warranty deed, under a normal sale condition, for 208500 dollars.

House `Id` 2 is the check that the first row is not the whole city: Veenker, quality 6, one story, built in 1976, sold for 181500.


In [2]:
# Locate the contest tables beside this notebook, or under the course root.
from pathlib import Path
import csv

def manifest_path(name):
    here = Path.cwd()
    for folder in [here, *here.parents]:
        nested = folder / "14-House Prices" / "data" / name
        direct = folder / "data" / name
        if nested.exists():
            return nested
        if direct.exists() and (folder / "data" / "data_description.txt").exists():
            return direct
    raise FileNotFoundError(name)

def read_manifest(name):
    with manifest_path(name).open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))

train = read_manifest("train.csv")
test = read_manifest("test.csv")
submission = read_manifest("sample_submission.csv")
print(len(train), len(test), len(submission))
print(train[0]["Id"], train[0]["SalePrice"])


1460 1459 1459
1 208500


In [3]:
# Check the two additions and the sale fields on house 1.
house = train[0]
basement = int(house["BsmtFinSF1"]) + int(house["BsmtFinSF2"]) + int(house["BsmtUnfSF"])
living = int(house["1stFlrSF"]) + int(house["2ndFlrSF"]) + int(house["LowQualFinSF"])
print(house["Neighborhood"], basement, living, house["SalePrice"])
assert house["Id"] == "1"
assert house["Neighborhood"] == "CollgCr"
assert house["MSSubClass"] == "60"
assert house["HouseStyle"] == "2Story"
assert house["Alley"] == "NA"
assert house["OverallQual"] == "7"
assert house["YearBuilt"] == "2003"
assert int(house["BsmtFinSF1"]) == 706
assert int(house["BsmtUnfSF"]) == 150
assert basement == 856 == int(house["TotalBsmtSF"])
assert int(house["1stFlrSF"]) == 856
assert int(house["2ndFlrSF"]) == 854
assert living == 1710 == int(house["GrLivArea"])
assert house["Fireplaces"] == "0"
assert house["FireplaceQu"] == "NA"
assert house["GarageCars"] == "2"
assert int(house["SalePrice"]) == 208500
other = train[1]
print(other["Id"], other["Neighborhood"], other["SalePrice"])
assert other["Id"] == "2"
assert other["Neighborhood"] == "Veenker"
assert int(other["SalePrice"]) == 181500


CollgCr 856 1710 208500
2 Veenker 181500


## Pitfall

Basement exposure `No` means the basement is there and has no exposure. `NA` is the codebook's token for no basement. House 1 uses `No`. Treating those two tokens as the same word throws away a basement of 856 square feet.

## Summary

House 1 is College Creek, quality 7, 1710 square feet above grade, sold for 208500 in February 2008. The basement parts add to 856 and the floors add to 1710.
